  version: '3'

  services:
    db:
      image: postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.dev
      networks:
        internal_net:
          ipv4_address: 172.28.1.7
#     web:
#       build: .
#       command: python manage.py runserver 0.0.0.0:8000
#       volumes:
#         - .:/code:Z
#       env_file:
#         - ./.env.dev
#       ports:
#         - "8000:8000"
#       depends_on:
#         - db
  volumes:
    postgres_data:

  networks:
    internal_net:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
