  version: '3'
    
  services:
    db_1:
      image: postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    db_2:
      image: postgres
      volumes:
      - postgres_data_2:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=postgres2
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code:Z
      ports:
        - "8000:8000"
      depends_on:
        - db_1
        - db_2
  volumes:
    postgres_data:
    postgres_data_2:
