version: '3.3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: italgold
    networks:
      internal_net:
        ipv4_address: 172.30.1.7

volumes:
  postgres_data:

networks:
  internal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
