  version: '3'

  services:
    db:
      image: postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.dev
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code:Z
      ports:
        - "8000:8000"
      depends_on:
        - db
  volumes:
    postgres_data:
