# Generated by Django 3.0.7 on 2020-06-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Leather')),
                ('image', models.CharField(blank=True, max_length=1000, verbose_name='Image')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Leather',
                'verbose_name_plural': 'Leathers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeatherSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Leather serial',
                'verbose_name_plural': 'Leather serials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Date last update')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Products')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('image', models.CharField(max_length=1000, verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('height', models.FloatField(null=True, verbose_name='Height')),
                ('width', models.FloatField(null=True, verbose_name='Width')),
                ('length', models.FloatField(null=True, verbose_name='Length')),
                ('deleted', models.BooleanField(default=False)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.ProductCategory')),
                ('inner_color',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inner_products',
                                   to='order.Leather', verbose_name='Inner color')),
                ('outer_color',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outer_products',
                                   to='order.Leather', verbose_name='Outer color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('height', models.FloatField(verbose_name='Height')),
                ('width', models.FloatField(verbose_name='Width')),
                ('length', models.FloatField(null=True, verbose_name='Length')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('inner_leather',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inner_order_units',
                                   to='order.Leather', verbose_name='Inner leather')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units',
                                            to='order.Order', verbose_name='Order')),
                ('outer_leather',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outer_order_units',
                                   to='order.Leather', verbose_name='Outer color')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_units',
                                   to='order.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order unit',
                'verbose_name_plural': 'Order units',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='leather',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leathers',
                                    to='order.LeatherSerial'),
        ),
    ]
