# Generated by Django 3.0.7 on 2020-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200625_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leather',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='leather',
            unique_together={('code', 'serial')},
        ),
    ]
