# Generated by Django 3.1.5 on 2021-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210314_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ManyToManyField(related_name='sub_categories', to='order.ProductCategory'),
        ),
    ]
