# Generated by Django 3.1.5 on 2021-03-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210314_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inner_leather',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outer_leather',
        ),
    ]
