# Generated by Django 3.1.5 on 2021-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210328_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leather',
            name='image',
            field=models.FileField(blank=True, upload_to='leathers', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products', verbose_name='Image'),
        ),
    ]
